<?php

namespace classes;

class Hero extends User
{
    private $_posRatings;
    private $_numRatings;
    private $_strength;
    private $_intellect;
    private $_energy;
    private $_speed;
    private $_powers;
    private $_realName;
    private $_hideRealName;

    /**
     * @param $_posRatings
     * @param $_numRatings
     * @param $_strength
     * @param $_intellect
     * @param $_energy
     * @param $_speed
     * @param $_powers
     * @param $_realName
     * @param $_hideRealName
     */
    public function __construct(int $_posRatings = 0, int $_numRatings = 1, int $_strength = 10, int $_intellect = 10, int $_energy = 10, int $_speed = 10,
                                array $_powers = [], string $_realName = '', bool $_hideRealName = true)
    {
        parent::__construct();

        $this->_posRatings = $_posRatings;
        $this->_numRatings = $_numRatings;
        $this->_strength = $_strength;
        $this->_intellect = $_intellect;
        $this->_energy = $_energy;
        $this->_speed = $_speed;
        $this->_powers = $_powers;
        $this->_realName = $_realName;
        $this->_hideRealName = $_hideRealName;
    }


    public function getNumRatings()
    {
        return $this->_numRatings;
    }

    /**
     * @param mixed $numRatings
     */
    public function setNumRatings($numRatings): void
    {
        $this->_numRatings = $numRatings;
    }

    /**
     * @return mixed
     */
    public function getPosRatings()
    {
        return $this->_posRatings;
    }

    /**
     * @param mixed $rating
     */
    public function setPosRatings($rating): void
    {
        $this->_posRatings = $rating;
    }

    /**
     * @return mixed
     */
    public function getStrength()
    {
        return $this->_strength;
    }

    /**
     * @param mixed $strength
     */
    public function setStrength($strength): void
    {
        $this->_strength = $strength;
    }

    /**
     * @return mixed
     */
    public function getIntellect()
    {
        return $this->_intellect;
    }

    /**
     * @param mixed $intellect
     */
    public function setIntellect($intellect): void
    {
        $this->_intellect = $intellect;
    }

    /**
     * @return mixed
     */
    public function getEnergy()
    {
        return $this->_energy;
    }

    /**
     * @param mixed $energy
     */
    public function setEnergy($energy): void
    {
        $this->_energy = $energy;
    }

    /**
     * @return mixed
     */
    public function getSpeed()
    {
        return $this->_speed;
    }

    /**
     * @param mixed $speed
     */
    public function setSpeed($speed): void
    {
        $this->_speed = $speed;
    }

    /**
     * @return array
     */
    public function getPowers(): array
    {
        return $this->_powers;
    }

    /**
     * @param array $powers
     */
    public function setPowers(array $powers): void
    {
        $this->_powers = $powers;
    }

    /**
     * @return mixed
     */
    public function getRealName()
    {
        return $this->_realName;
    }

    /**
     * @param mixed $realName
     */
    public function setRealName($realName): void
    {
        $this->_realName = $realName;
    }

    /**
     * @return bool
     */
    public function getHideRealName(): bool
    {
        return $this->_hideRealName;
    }

    /**
     * @param bool $hideRealName
     */
    public function setHideRealName(bool $hideRealName): void
    {
        $this->_hideRealName = $hideRealName;
    }

    public function setUserId($userId)
    {
        parent::setUserId($userId);
    }

    public function getUserId()
    {
        return parent::getUserId(); // TODO: Change the autogenerated stub
    }
}
